/**
 * Seeded demo data for mock mode.
 *
 * Single source of truth the mock services read from. Locations span PA-05
 * neighborhoods (Bryn Mawr, Wynnewood, Gladwyne, Ardmore, Lower Merion) to make
 * the community-impact story concrete.
 */

import {
  Application,
  AppNotification,
  Job,
  Report,
  Review,
  SupportTicket,
  UserProfile,
  UserRef,
} from '@/types/domain';

const hoursAgo = (h: number): string =>
  new Date(Date.now() - h * 3600_000).toISOString();
const daysAgo = (d: number): string => hoursAgo(d * 24);

// ── Users ────────────────────────────────────────────────────────────────────
export const currentUser: UserProfile = {
  id: 'u_sarah',
  name: 'Sarah Mitchell',
  avatarUrl: null,
  neighborhood: 'Bryn Mawr',
  roles: ['customer', 'helper', 'admin'], // admin enables the moderation console in demo
  ageGroup: 'adult',
  rating: 4.9,
  jobsCount: 12,
  reputationScore: 94,
  isTrusted: true,
  verification: {
    emailVerified: true,
    phoneAdded: true,
    photoAdded: false,
    schoolEmailVerified: false,
    parentApproved: false,
  },
  parentApprovalStatus: 'not_required',
  phoneNumber: '(610) 555-0142',
  preferredContactMethod: 'text',
  skills: ['Reliability', 'Communication', 'Yard work', 'Tutoring'],
  preferredCategories: ['tutoring', 'snow_removal', 'pet_care'],
  bio: 'Long-time Bryn Mawr resident. Happy to help neighbors and grateful for a hand when I need one.',
  isAdmin: true,
  memberSince: daysAgo(420),
};

export const users: UserProfile[] = [
  currentUser,
  {
    id: 'u_diego',
    name: 'Diego Ramirez',
    avatarUrl: null,
    neighborhood: 'Lower Merion',
    roles: ['helper'],
    ageGroup: 'adult',
    rating: 4.9,
    jobsCount: 87,
    reputationScore: 96,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: true,
      schoolEmailVerified: false,
      parentApproved: false,
    },
    parentApprovalStatus: 'not_required',
    phoneNumber: '(610) 555-0188',
    preferredContactMethod: 'phone',
    skills: ['Snow removal', 'Reliability', 'Time management', 'Customer service'],
    preferredCategories: ['snow_removal', 'lawn_care', 'moving_help'],
    memberSince: daysAgo(610),
  },
  {
    id: 'u_alex',
    name: 'Alex Morgan',
    avatarUrl: null,
    neighborhood: 'Bryn Mawr',
    roles: ['helper'],
    ageGroup: 'adult',
    rating: 4.9,
    jobsCount: 120,
    reputationScore: 98,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: true,
      schoolEmailVerified: false,
      parentApproved: false,
    },
    parentApprovalStatus: 'not_required',
    phoneNumber: '(610) 555-0123',
    preferredContactMethod: 'text',
    skills: ['Yard work', 'Pet care', 'Reliability', 'Communication'],
    preferredCategories: ['yard_work', 'pet_care', 'errands'],
    memberSince: daysAgo(700),
  },
  {
    id: 'u_jordan',
    name: 'Jordan Lee',
    avatarUrl: null,
    neighborhood: 'Ardmore',
    roles: ['helper'],
    ageGroup: 'teen',
    rating: 4.8,
    jobsCount: 14,
    reputationScore: 88,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: true,
      schoolEmailVerified: true,
      parentApproved: true,
    },
    parentApprovalStatus: 'approved',
    parentName: 'Karen Lee',
    parentEmail: 'karen.lee@example.com',
    schoolEmail: 'jordan.lee@students.lmsd.org',
    phoneNumber: '(610) 555-0170',
    preferredContactMethod: 'text',
    skills: ['Snow shoveling', 'Time management', 'Reliability'],
    preferredCategories: ['snow_removal', 'leaf_cleanup', 'dog_walking'],
    bio: 'Sophomore at Lower Merion HS. Reliable and happy to help nearby neighbors after school.',
    memberSince: daysAgo(140),
  },
  {
    id: 'u_jessica',
    name: 'Jessica Tran',
    avatarUrl: null,
    neighborhood: 'Wynnewood',
    roles: ['helper'],
    ageGroup: 'teen',
    rating: 4.8,
    jobsCount: 9,
    reputationScore: 86,
    isTrusted: false,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: true,
      schoolEmailVerified: true,
      parentApproved: false,
    },
    parentApprovalStatus: 'pending',
    schoolEmail: 'jessica.tran@students.lmsd.org',
    phoneNumber: '(610) 555-0155',
    preferredContactMethod: 'text',
    skills: ['Tutoring', 'Communication', 'Pet care'],
    preferredCategories: ['tutoring', 'pet_care', 'plant_watering'],
    memberSince: daysAgo(95),
  },
  {
    id: 'u_marcus',
    name: 'Marcus Lee',
    avatarUrl: null,
    neighborhood: 'Gladwyne',
    roles: ['customer'],
    ageGroup: 'adult',
    rating: 4.7,
    jobsCount: 6,
    reputationScore: 88,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: false,
      schoolEmailVerified: false,
      parentApproved: false,
    },
    parentApprovalStatus: 'not_required',
    phoneNumber: '(610) 555-0199',
    preferredContactMethod: 'phone',
    skills: [],
    preferredCategories: [],
    memberSince: daysAgo(120),
  },
  {
    id: 'u_nina',
    name: 'Nina Patel',
    avatarUrl: null,
    neighborhood: 'Wynnewood',
    roles: ['customer'],
    ageGroup: 'adult',
    rating: 4.8,
    jobsCount: 9,
    reputationScore: 90,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: true,
      schoolEmailVerified: false,
      parentApproved: false,
    },
    parentApprovalStatus: 'not_required',
    phoneNumber: '(610) 555-0111',
    preferredContactMethod: 'text',
    skills: [],
    preferredCategories: [],
    memberSince: daysAgo(220),
  },
  {
    id: 'u_eleanor',
    name: 'Eleanor Whitfield',
    avatarUrl: null,
    neighborhood: 'Ardmore',
    roles: ['customer'],
    ageGroup: 'adult',
    rating: 5.0,
    jobsCount: 4,
    reputationScore: 92,
    isTrusted: true,
    verification: {
      emailVerified: true,
      phoneAdded: true,
      photoAdded: false,
      schoolEmailVerified: false,
      parentApproved: false,
    },
    parentApprovalStatus: 'not_required',
    phoneNumber: '(610) 555-0166',
    preferredContactMethod: 'phone',
    skills: [],
    preferredCategories: [],
    bio: 'Retired teacher in Ardmore. Grateful for a little help around the house.',
    memberSince: daysAgo(60),
  },
];

export const userRef = (u: UserProfile): UserRef => ({
  id: u.id,
  name: u.name,
  avatarUrl: u.avatarUrl,
  rating: u.rating,
  jobsCount: u.jobsCount,
  isTrusted: u.isTrusted,
});

const byId = (id: string): UserProfile =>
  users.find((u) => u.id === id) ?? currentUser;

// ── Jobs ─────────────────────────────────────────────────────────────────────
export const jobs: Job[] = [
  // --- Current user's posted jobs (customer view) ---
  {
    id: 'j_snow_sarah',
    customerId: 'u_sarah',
    customer: userRef(currentUser),
    category: 'snow_removal',
    title: 'Snow shoveling',
    description:
      'Looking for a reliable neighbor to shovel my 2-car driveway and front walkway after the storm.',
    pay: 35,
    payType: 'fixed',
    status: 'reviewing',
    safetyTier: 'caution',
    requiresAdultSupervision: false,
    equipmentStatus: 'yes',
    equipmentDetails: 'Snow shovel and salt provided.',
    communityTags: ['weather_related', 'quick_task'],
    neighborhood: 'Bryn Mawr',
    distanceMiles: 0,
    location: { lat: 40.0212, lng: -75.3149 },
    scheduledFor: 'Today, 2 PM',
    isTimeFlexible: false,
    durationMinutes: 90,
    estimatedDuration: '1-2 hours',
    photos: [],
    applicantsCount: 3,
    createdWithSeniorMode: false,
    isPaused: false,
    createdAt: hoursAgo(5),
  },
  {
    id: 'j_grocery_sarah',
    customerId: 'u_sarah',
    customer: userRef(currentUser),
    category: 'errands',
    title: 'Grocery run',
    description: 'Pick up a short grocery list from Acme and drop off at my door.',
    pay: 20,
    payType: 'fixed',
    status: 'accepted',
    assignedHelperId: 'u_alex',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'not_needed',
    communityTags: ['quick_task'],
    neighborhood: 'Bryn Mawr',
    distanceMiles: 0,
    location: { lat: 40.0219, lng: -75.3151 },
    scheduledFor: 'Tomorrow, 10 AM',
    isTimeFlexible: true,
    durationMinutes: 60,
    estimatedDuration: '1 hour',
    photos: [],
    applicantsCount: 1,
    createdWithSeniorMode: false,
    isPaused: false,
    createdAt: daysAgo(1),
  },

  // --- Other people's jobs (helper feed) ---
  {
    id: 'j_shovel_walkway',
    customerId: 'u_nina',
    customer: userRef(byId('u_nina')),
    category: 'snow_removal',
    title: 'Shovel front walkway',
    description:
      'Need my front walkway and steps cleared. Salt provided. Should take under an hour.',
    pay: 30,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'yes',
    equipmentDetails: 'Shovel and salt provided.',
    communityTags: ['weather_related', 'quick_task'],
    neighborhood: 'Bryn Mawr',
    distanceMiles: 0.6,
    location: { lat: 40.0205, lng: -75.314 },
    scheduledFor: 'Today, 4 PM',
    isTimeFlexible: false,
    durationMinutes: 45,
    estimatedDuration: 'Under 1 hour',
    photos: [],
    applicantsCount: 2,
    createdWithSeniorMode: false,
    matchScore: 96,
    isPaused: false,
    createdAt: hoursAgo(2),
  },
  {
    id: 'j_algebra',
    customerId: 'u_nina',
    customer: userRef(byId('u_nina')),
    category: 'tutoring',
    title: 'Algebra tutoring',
    description:
      'High-school sophomore needs help preparing for an algebra II exam. Weekly sessions possible.',
    pay: 25,
    payType: 'hourly',
    status: 'open',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'not_needed',
    communityTags: ['student_friendly', 'recurring_help'],
    neighborhood: 'Wynnewood',
    distanceMiles: 1.1,
    location: { lat: 40.0051, lng: -75.2935 },
    scheduledFor: 'This week',
    isTimeFlexible: true,
    durationMinutes: 60,
    estimatedDuration: '1 hour',
    photos: [],
    applicantsCount: 1,
    createdWithSeniorMode: false,
    matchScore: 94,
    isPaused: false,
    createdAt: hoursAgo(4),
  },
  {
    id: 'j_pool',
    customerId: 'u_marcus',
    customer: userRef(byId('u_marcus')),
    category: 'pool_cleaning',
    title: 'Pool cleaning assistance',
    description:
      'Help skim, vacuum, and balance chemicals for an in-ground pool. Some experience preferred.',
    pay: 50,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'adult_supervision',
    safetyNotes: 'Involves pool chemicals — adult supervision recommended.',
    requiresAdultSupervision: true,
    equipmentStatus: 'some',
    equipmentDetails: 'Pool net and vacuum provided; chemicals handled by owner.',
    communityTags: [],
    neighborhood: 'Gladwyne',
    distanceMiles: 2.4,
    location: { lat: 40.0301, lng: -75.2776 },
    scheduledFor: 'Saturday morning',
    isTimeFlexible: false,
    durationMinutes: 150,
    estimatedDuration: '2-3 hours',
    photos: [],
    applicantsCount: 0,
    createdWithSeniorMode: false,
    matchScore: 82,
    isPaused: false,
    createdAt: hoursAgo(6),
  },
  {
    id: 'j_gutter',
    customerId: 'u_marcus',
    customer: userRef(byId('u_marcus')),
    category: 'yard_work',
    title: 'Gutter cleaning (ladder)',
    description:
      'Clear leaves from second-story gutters. Requires comfort on a tall ladder.',
    pay: 80,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'eighteen_plus_only',
    safetyNotes: 'Ladder work at height — helpers under 18 cannot apply.',
    requiresAdultSupervision: false,
    equipmentStatus: 'no',
    equipmentDetails: 'Bring your own ladder and gloves.',
    communityTags: ['weather_related'],
    neighborhood: 'Gladwyne',
    distanceMiles: 2.6,
    location: { lat: 40.0309, lng: -75.2762 },
    scheduledFor: 'This weekend',
    isTimeFlexible: true,
    durationMinutes: 120,
    estimatedDuration: '2 hours',
    photos: [],
    applicantsCount: 0,
    createdWithSeniorMode: false,
    matchScore: 70,
    isPaused: false,
    createdAt: hoursAgo(9),
  },
  {
    id: 'j_groceries_eleanor',
    customerId: 'u_eleanor',
    customer: userRef(byId('u_eleanor')),
    category: 'errands',
    title: 'Carry groceries inside',
    description:
      'Need a hand carrying grocery bags from the car into the kitchen. Quick and easy.',
    pay: 15,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'not_needed',
    communityTags: ['senior_help', 'quick_task'],
    neighborhood: 'Ardmore',
    distanceMiles: 1.7,
    location: { lat: 40.0072, lng: -75.2899 },
    scheduledFor: 'Thursday afternoon',
    isTimeFlexible: true,
    durationMinutes: 30,
    estimatedDuration: '30 minutes',
    photos: [],
    applicantsCount: 1,
    createdWithSeniorMode: true,
    familyContact: {
      name: 'Robert Whitfield',
      phone: '(610) 555-0167',
      notify: true,
    },
    matchScore: 90,
    isPaused: false,
    createdAt: hoursAgo(7),
  },
  {
    id: 'j_dog',
    customerId: 'u_nina',
    customer: userRef(byId('u_nina')),
    category: 'dog_walking',
    title: 'Dog walking',
    description: 'Friendly labrador needs a 30-minute walk on weekday afternoons.',
    pay: 18,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'yes',
    equipmentDetails: 'Leash and waste bags provided.',
    communityTags: ['recurring_help', 'student_friendly'],
    neighborhood: 'Wynnewood',
    distanceMiles: 1.4,
    location: { lat: 40.006, lng: -75.291 },
    scheduledFor: 'Weekday afternoons',
    isTimeFlexible: true,
    durationMinutes: 30,
    estimatedDuration: '30 minutes',
    photos: [],
    applicantsCount: 5,
    createdWithSeniorMode: false,
    matchScore: 87,
    isPaused: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'j_leaves_eleanor',
    customerId: 'u_eleanor',
    customer: userRef(byId('u_eleanor')),
    category: 'leaf_cleanup',
    title: 'Rake and bag leaves',
    description: 'Front yard leaf cleanup. Bags provided. A couple hours of work.',
    pay: 40,
    payType: 'fixed',
    status: 'open',
    safetyTier: 'teen_safe',
    requiresAdultSupervision: false,
    equipmentStatus: 'some',
    equipmentDetails: 'Bags provided; bring a rake if you have one.',
    communityTags: ['senior_help', 'weather_related'],
    neighborhood: 'Ardmore',
    distanceMiles: 1.8,
    location: { lat: 40.0068, lng: -75.2905 },
    scheduledFor: 'Saturday',
    isTimeFlexible: true,
    durationMinutes: 120,
    estimatedDuration: '2 hours',
    photos: [],
    applicantsCount: 0,
    createdWithSeniorMode: true,
    matchScore: 85,
    isPaused: false,
    createdAt: daysAgo(1),
  },
  // A completed job (feeds impact stats)
  {
    id: 'j_completed_1',
    customerId: 'u_marcus',
    customer: userRef(byId('u_marcus')),
    category: 'lawn_care',
    title: 'Lawn mowing',
    description: 'Front and back lawn mow.',
    pay: 45,
    payType: 'fixed',
    status: 'completed',
    assignedHelperId: 'u_diego',
    safetyTier: 'caution',
    requiresAdultSupervision: false,
    equipmentStatus: 'yes',
    communityTags: [],
    neighborhood: 'Gladwyne',
    distanceMiles: 1.9,
    location: { lat: 40.0312, lng: -75.279 },
    scheduledFor: 'Last week',
    isTimeFlexible: true,
    durationMinutes: 90,
    estimatedDuration: '1-2 hours',
    photos: [],
    applicantsCount: 3,
    createdWithSeniorMode: false,
    isPaused: false,
    createdAt: daysAgo(8),
  },
];

// ── Applications (to the current user's posted snow job) ─────────────────────
export const applications: Application[] = [
  {
    id: 'app_1',
    jobId: 'j_snow_sarah',
    helperId: 'u_alex',
    helper: userRef(byId('u_alex')),
    message:
      'Hi! I live nearby and can bring my own shovel and salt. Available this afternoon.',
    proposedPay: 35,
    availability: 'Today after 1 PM',
    status: 'pending',
    createdAt: hoursAgo(4),
  },
  {
    id: 'app_2',
    jobId: 'j_snow_sarah',
    helperId: 'u_diego',
    helper: userRef(byId('u_diego')),
    message:
      'Happy to help — I’ve done dozens of driveways this season. Can start within the hour.',
    proposedPay: 40,
    availability: 'Today, anytime',
    status: 'pending',
    createdAt: hoursAgo(3),
  },
  {
    id: 'app_3',
    jobId: 'j_snow_sarah',
    helperId: 'u_jordan',
    helper: userRef(byId('u_jordan')),
    message: 'I can come by after school today. Parent-approved and reliable!',
    availability: 'Today after 3 PM',
    status: 'pending',
    createdAt: hoursAgo(2),
  },
];

// ── Reviews ──────────────────────────────────────────────────────────────────
export const reviews: Review[] = [
  {
    id: 'rev_1',
    jobId: 'j_completed_1',
    reviewerId: 'u_marcus',
    revieweeId: 'u_diego',
    ratings: { reliability: 5, quality: 5, communication: 5, professionalism: 5 },
    comment: 'Diego did a fantastic job and was super communicative. Highly recommend!',
    createdAt: daysAgo(7),
  },
  {
    id: 'rev_2',
    jobId: 'j_old_2',
    reviewerId: 'u_nina',
    revieweeId: 'u_alex',
    ratings: { reliability: 5, quality: 5, communication: 4, professionalism: 5 },
    comment: 'Alex was on time and did great work. Will hire again.',
    createdAt: daysAgo(18),
  },
  {
    id: 'rev_3',
    jobId: 'j_old_3',
    reviewerId: 'u_eleanor',
    revieweeId: 'u_jordan',
    ratings: { reliability: 5, quality: 5, communication: 5, professionalism: 5 },
    comment: 'Jordan was polite, punctual, and a huge help. A wonderful young neighbor.',
    createdAt: daysAgo(12),
  },
];

// ── Notifications (for the current user) ─────────────────────────────────────
export const notifications: AppNotification[] = [
  {
    id: 'n_1',
    userId: 'u_sarah',
    type: 'application_received',
    title: 'New application',
    body: 'Diego Ramirez applied to your "Snow shoveling" job.',
    read: false,
    createdAt: hoursAgo(3),
  },
  {
    id: 'n_2',
    userId: 'u_sarah',
    type: 'job_match',
    title: 'New job match',
    body: 'A "Shovel front walkway" job near you is a 96% match.',
    read: false,
    createdAt: hoursAgo(3),
  },
  {
    id: 'n_3',
    userId: 'u_sarah',
    type: 'application_accepted',
    title: 'You’re hired!',
    body: 'Your application for "Grocery run" was accepted.',
    read: true,
    createdAt: daysAgo(1),
  },
  {
    id: 'n_4',
    userId: 'u_sarah',
    type: 'safety',
    title: 'Stay safe',
    body: 'Always meet in a public place for first-time jobs. Tap to review safety tips.',
    read: true,
    createdAt: daysAgo(3),
  },
];

// ── Reports (for the admin console) ──────────────────────────────────────────
export const reports: Report[] = [
  {
    id: 'rep_1',
    reporterId: 'u_nina',
    reportedUserId: 'u_marcus',
    jobId: 'j_gutter',
    category: 'dangerous_task',
    description:
      'This gutter job looks risky for the listed pay and might attract underage helpers.',
    riskLevel: 'high',
    aiSummary:
      'Task involves ladder work at height. Recommend enforcing 18+ and adding safety notes.',
    status: 'open',
    createdAt: hoursAgo(10),
  },
  {
    id: 'rep_2',
    reporterId: 'u_jordan',
    reportedUserId: 'u_marcus',
    category: 'inappropriate_contact',
    description: 'Received an off-platform message that felt pushy.',
    riskLevel: 'medium',
    aiSummary: 'Possible off-platform contact attempt. Review and warn if confirmed.',
    status: 'reviewing',
    createdAt: daysAgo(2),
  },
];

// ── Support tickets (for the admin console) ──────────────────────────────────
export const supportTickets: SupportTicket[] = [
  {
    id: 'tic_1',
    userId: 'u_eleanor',
    category: 'account',
    subject: 'How do I add a family contact?',
    message:
      'My daughter wants to be notified when someone accepts my jobs. How do I set that up?',
    status: 'open',
    createdAt: daysAgo(1),
  },
  {
    id: 'tic_2',
    userId: 'u_jessica',
    category: 'safety',
    subject: 'Parent approval pending',
    message: 'I submitted parent approval a day ago — when will it be active?',
    status: 'in_progress',
    createdAt: daysAgo(2),
  },
];

export { byId as findUserById };
